DEVICE          : cuda              # device used for training and evaluation (cpu, cuda, cuda0, cuda1, ...)
SAVE_DIR        : 'output'         # output folder name used for saving the model, logs and inference results

MODEL:
  NAME          : CMNeXt                                            # name of the model you are using
  BACKBONE      : SwinTransformer-B  # or SwinTransformer-L                                         # model variant
  #PRETRAINED    : 'checkpoints/pretrained/segformer/mit_b5.pth'     # backbone model's weight
  PRETRAINED: ''
  RESUME        : ''                                                # checkpoint file

DATASET:
  NAME          : PST                                          # dataset name to be trained with (camvid, cityscapes, ade20k)
  ROOT          : 'data/PST900'                            # dataset root path                              # dataset root path
  IGNORE_LABEL  : 255
  MODALS        : ['img', 'thermal']

TRAIN:
  IMAGE_SIZE    : [480, 640]
  #IMAGE_SIZE    : [720, 720]      # training image size in (h, w)
  BATCH_SIZE    : 4               # batch size used to train
  EPOCHS        : 200             # number of epochs to train
  EVAL_START    : 150             # evaluation interval during training
  EVAL_INTERVAL : 1               # evaluation interval during training
  AMP           : false           # use AMP in training
  DDP           : false            # use DDP trai

LOSS:
  NAME          : CrossEntropy     # loss function name (ohemce, ce, dice)   OHEM?
  CLS_WEIGHTS   : false            # use class weights in loss calculation

OPTIMIZER:
  NAME          : adamw           # optimizer name
  #LR            : 0.00006         # initial learning rate used in optimizer
  LR            : 0.0006

  #WEIGHT_DECAY  : 0.01            # decay rate used in optimizer
  WEIGHT_DECAY  : 0.01
  TRAIN_TYPE    : Adapter

SCHEDULER:
  NAME          : warmuppolylr    # scheduler name
  POWER         : 0.9             # scheduler power
  WARMUP        : 10              # warmup epochs used in scheduler
  WARMUP_RATIO  : 0.1             # warmup ratio


EVAL:
  MODEL_PATH    : 'Your checkpoint path!!'
  IMAGE_SIZE    : [720, 1280]      # evaluation image size in (h, w)
  BATCH_SIZE    : 1               # batch size used to train
  MSF:
    ENABLE      : true                                   # multi-scale and flip evaluation
    FLIP        : true                                    # use flip in evaluation
    SCALES      : [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]       # scales used in MSF evaluation